spring.application.name=jobhunter

spring.jpa.hibernate.ddl-auto=update
spring.datasource.url=jdbc:mysql://localhost:3306/job_hunter
spring.datasource.username=root
spring.datasource.password=Quan!@2404
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQL8Dialect
###
#config jwt
hoidanit.jwt.base64-secret=TRrx3ZoD9xgevlM73MU8/ay9VO+8RJ7NjvFh5Ab0xoTsKzuPYwCOKDZugGYsVxroYRfP94DH6jBxBhFyBPaQQQ==
#expiration : 1 day (seconds = 24 * 60 * 60)
# 100 days
hoidanit.jwt.access-token-validity-in-seconds=8640000
hoidanit.jwt.refresh-token-validity-in-seconds=8640000

# Redis Configuration
spring.data.redis.host=redis-13552.c16.us-east-1-2.ec2.redns.redis-cloud.com
spring.data.redis.port=13552
spring.data.redis.password=nTKWlMxcqvf3xWKnBOr9WHK93KMNa8DZ

# gmail setup
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=phanquan240402@gmail.com
spring.mail.password=xcykiqhddfkxlwkw
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.from=phanquan240402@gmail.comp0

#upload file
hoidanit.upload-file.base-uri=file:///D:/Workspace/jobhunter/upload/
spring.servlet.multipart.max-file-size=50MB
spring.servlet.multipart.max-request-size=50MB

###
#config pagination
#start page = 1
spring.data.web.pageable.one-indexed-parameters=true